/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashBoard: typeof import('./src/components/DashBoard.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconIFG: typeof import('./src/components/icons/IconIFG.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpArrowDownBold: typeof import('~icons/ep/arrow-down-bold')['default']
    ImgWindow: typeof import('./src/components/ImgWindow.vue')['default']
    ItemBox: typeof import('./src/components/itemBox.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RouteArrow: typeof import('./src/components/routeArrow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollBox: typeof import('./src/components/ScrollBox.vue')['default']
  }
}
